class MyntraLocators:
    myntra_logo = "div.desktop-logoContainer"
    home_furnishing = "//h1[normalize-space()='Home Furnishing']"
    filters_men = "//label[normalize-space()='Men']"
    filters_women = "//label[normalize-space()='Women']"
    filters_boys = "//input[@value='boys,boys girls']"
    filters_girls = "//label[normalize-space()='Girls']"
    bundles = ".atsa-upArrow.sprites-arrowUpBold.myntraweb-sprite"
    bundles_inside = "//label[contains(text(),'Bundles')]"
    singleStyles = "//label[contains(text(),'Single Styles')]"
    countryOfOrigin = "//h4[normalize-space()='Country of Origin']"
    allCountries = "//label[normalize-space()='All Countries']"
    india = "input[value='India']"
