class MyntraLocators:
    myntra_logo = "div.desktop-logoContainer"
    home_furnishing = "//h1[normalize-space()='Home Furnishing']"
    filters_men = "//label[normalize-space()='Men']"
    filters_women = "//label[normalize-space()='Women']"
    filters_boys = "//input[@value='boys,boys girls']"
    filters_girls = "//label[normalize-space()='Girls']"
    clear_all = "//span[@class='header-clearAllBtn']"
    bundles = ".atsa-upArrow.sprites-arrowUpBold.myntraweb-sprite"
    bundles_option = "//label[contains(text(),'Bundles')]"
    bundles_singleStyles = "//label[contains(text(),'Single Styles')]"
    countryofOrigin = "//h4[normalize-space()='Country of Origin']"
    allCountries_option = "//label[normalize-space()='All Countries']"
    india_option = "input[value='India']"
    size = "//h4[normalize-space()='Size']"
